name: Build for Windows ARM64

on:
  push:

jobs:
  build-windows-arm64:
    name: Build
    runs-on: ubuntu-latest
    env:
      llvm_path: "${{ github.workspace }}/llvm-mingw"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install \
            gcc git cmake ninja-build pkg-config p7zip libtool make colormake gettext automake autoconf autogen autopoint patch wx-common
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20231128/llvm-mingw-20231128-ucrt-ubuntu-20.04-x86_64.tar.xz
          tar -xf llvm-mingw-*.tar.xz
          rm llvm-mingw-*.tar.xz
          mv llvm-mingw-* llvm-mingw
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          
      - name: Install libraries from vcpkg
        run: |
          export PATH=${{ env.llvm_path }}/bin:$PATH
          cd vcpkg
          sed -i 's/OPTIONS/OPTIONS\n--disable-hardware-acceleration/g' ports/libgnutls/portfile.cmake
          git apply ${{ github.workspace }}/patches/vcpkg-disable-asm-for-arm32.patch
          # tell vcpkg to only build Release variants of the dependencies
          mkdir triplets_overlay
          cp triplets/community/arm64-mingw-static.cmake triplets_overlay/arm64-mingw-static-release.cmake
          cp triplets/community/arm-mingw-static.cmake triplets_overlay/arm-mingw-static-release.cmake
          echo "set(VCPKG_BUILD_TYPE release)" >> triplets_overlay/arm64-mingw-static-release.cmake
          echo "set(VCPKG_BUILD_TYPE release)" >> triplets_overlay/arm-mingw-static-release.cmake
          # clear buildtrees after each package installation to reduce disk space requirements
          packages="libgnutls sqlite3"
          ./vcpkg upgrade \
            --overlay-triplets=triplets_overlay \
            --no-dry-run
          ./vcpkg install \
            --overlay-triplets=triplets_overlay \
            --clean-after-build \
            --triplet=arm64-mingw-static-release \
            $packages
          #./vcpkg install \
          #  --overlay-triplets=triplets_overlay \
          #  --clean-after-build \
          #  --triplet=arm-mingw-static-release \
          #  $packages
          cd ${{ github.workspace }}/vcpkg/installed/arm64-mingw-static-release/lib
          ln -s libzlib.a libz.a
          # cd ${{ github.workspace }}/vcpkg/installed/arm-mingw-static-release/lib
          # ln -s libzlib.a libz.a

      - name: Build filezilla
        run: |
          chmod 755 build.sh
          ./build.sh arm64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: filezilla_server_${{ env.filezilla_server_version }}_arm64
          path: |
            ./filezilla_*.zip

      - name: Batch release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./filezilla_*.zip
